name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  TRACKER_API_URL: ${{ vars.TRACKER_API_URL }}

jobs:
  test_matrix:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: ${{ github.event.repository.name }}.exe
            suffix: ".exe"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup component add clippy
      - run: cargo check --release
      - run: cargo fmt --check
      - run: cargo test --release
      - run: cargo clippy --release -- -Dwarnings
      - run: cargo build --release
      - if: ${{matrix.artifact_name}}
        name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/release/irminsul${{ matrix.suffix }}
